[package]
name = "zenn_github_migrator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

dotenv = "0.15.0"
glob = "0.3.0"
anyhow = "1.0.44"
